[project]
name = "harpspol"
version = "0.1.0"
description = "Demodulate S2D from HARPSPOL, made by the ESPRESSO pipeline"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astropy>=7.0.1",
    "ipython>=8.32.0",
    "matplotlib>=3.10.0",
    "scipy>=1.15.2",
]
